// <auto-generated />
using BeingBeing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BeingBeing.Migrations
{
    [DbContext(typeof(BeingBeingContext))]
    [Migration("20180514181645_changedtemperature")]
    partial class changedtemperature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeingBeing.Models.Doings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateState");

                    b.Property<string>("Doing");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Notes");

                    b.Property<int>("Temperature");

                    b.Property<string>("Weather");

                    b.HasKey("ID");

                    b.ToTable("Doings");
                });

            modelBuilder.Entity("BeingBeing.Models.States", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateState");

                    b.Property<string>("Location");

                    b.Property<string>("Notes");

                    b.Property<string>("State");

                    b.Property<string>("Temperature");

                    b.Property<string>("Weather");

                    b.HasKey("ID");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
